
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 05 07:56:57 COT 2017
//----------------------------------------------------

package ejemplo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 21;
  public static final int headb = 25;
  public static final int heada = 24;
  public static final int DIFERENTE = 2;
  public static final int ulb = 36;
  public static final int ula = 35;
  public static final int LLAVEDER = 17;
  public static final int INT = 19;
  public static final int FOR = 18;
  public static final int titleb = 27;
  public static final int htmlb = 23;
  public static final int titlea = 26;
  public static final int htmla = 22;
  public static final int MENORIGUAL = 4;
  public static final int IGUAL = 9;
  public static final int MENOSNUM = 5;
  public static final int pb = 32;
  public static final int pa = 31;
  public static final int MASNUM = 7;
  public static final int ID = 20;
  public static final int MAYORIGUAL = 3;
  public static final int PYCOMA = 12;
  public static final int EOF = 0;
  public static final int PARIZQ = 14;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int ilb = 38;
  public static final int ila = 37;
  public static final int MENOR = 11;
  public static final int bodyb = 29;
  public static final int cb = 40;
  public static final int MAYOR = 10;
  public static final int bodya = 28;
  public static final int ca = 39;
  public static final int LLAVEIZQ = 16;
  public static final int MENOSUNO = 6;
  public static final int hr = 30;
  public static final int MASUNO = 8;
  public static final int PARDER = 15;
  public static final int h1b = 34;
  public static final int h1a = 33;
}

